# Generated by Django 5.1.1 on 2024-09-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(default='Другое', max_length=100),
        ),
    ]
