# Generated by Django 5.1.1 on 2024-09-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Внедорожник', 'Внедорожник'), ('Седан', 'Седан'), ('Купе', 'Купе'), ('Хэтчбек', 'Хэтчбек')], default='SEDAN', max_length=100),
        ),
    ]
